
name: vpt

from:
  model: null
  weights: ${oc.env:JARVISBASE_PRETRAINED}/bc-early-game-2x.weights

policy_kwargs: 
  active_reward_monitors: 
    env_reward: 1
  attention_heads: 16
  attention_mask_style: clipped_causal
  attention_memory_size: 256
  hidsize: 2048
  init_norm_kwargs:
    batch_norm: False
    group_norm_groups: 1
  n_recurrence_layers: 4
  only_img_input: True
  pointwise_ratio: 4
  pointwise_use_activation: False
  recurrence_is_residual: True
  recurrence_type: transformer
  timesteps: 128
  use_pointwise_layer: True
  use_pre_lstm_ln: False 
  # below are our custom configs
  condition_embedding: 
    name: 'text_embedding' 
    condition_dim: 512
  backbone_kwargs:
    name: 'EFFICIENTNET'
    version: 'efficientnet-b0'
    resolution: 224
    pooling: True
    atten: 'simple'  # simple, xatten
  condition_before_vision: True
  # abandon
  past_obs_fusion: # null
    num_past_obs: 9
    num_heads: 4

  cursor_on: False
  posbox_on: False
  recipe_on: True
  recipe_start_on: True
  recipe_start_dim: 46
  recipe_end_dim: 46
  cursor_loss_scale: 100
  use_film: False
  fuse_cond_hidden: True
  # abandon
  item_on: False
  item_mode: index

pi_head_kwargs: 
  temperature: 2.0

auxiliary_head_kwargs:
  temp_rank_head:
    enable: False
    num_inter_samples: 20
    num_intra_samples: 20
    interval: 3
    condition_dim: 512
    enable_condition: True
    enable_diff_traj: True
    compare_method: 'scalar'
    vision_feature: 'vi_latent'
